package ems;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class CustomerHome extends javax.swing.JFrame {

    /**
     * Creates new form CustomerHome
     */
    public CustomerHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOut = new javax.swing.JButton();
        ContactUs = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MakeYourBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SignUpNow1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOut.setBackground(new java.awt.Color(207, 179, 138));
        LogOut.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        LogOut.setForeground(new java.awt.Color(84, 64, 40));
        LogOut.setText("Log Out");
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 15, 130, -1));

        ContactUs.setBackground(new java.awt.Color(207, 179, 138));
        ContactUs.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        ContactUs.setForeground(new java.awt.Color(84, 64, 40));
        ContactUs.setText("Contact Us");
        ContactUs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContactUs.setBorderPainted(false);
        ContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsActionPerformed(evt);
            }
        });
        getContentPane().add(ContactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 15, 130, -1));

        jButton2.setBackground(new java.awt.Color(207, 179, 138));
        jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(84, 64, 40));
        jButton2.setText("Bookings");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 15, 130, -1));

        jButton1.setBackground(new java.awt.Color(207, 179, 138));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(84, 64, 40));
        jButton1.setText("Home");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, 130, -1));

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome Back");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\College\\Sophomore Year\\PL-2\\EMS 3\\Images\\lol.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jLabel2.setBackground(new java.awt.Color(48, 37, 21));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setText("Don't Miss Our Most Famous Bookings");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 560, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\College\\Sophomore Year\\PL-2\\EMS 3\\Images\\conf.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 240, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\College\\Sophomore Year\\PL-2\\EMS 3\\Images\\theatre.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 260, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\College\\Sophomore Year\\PL-2\\EMS 3\\Images\\wedding.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 270, -1));

        jLabel8.setBackground(new java.awt.Color(48, 37, 21));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setText("Conferences - Helwan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 220, 60));
        jLabel8.getAccessibleContext().setAccessibleName("");

        jLabel9.setBackground(new java.awt.Color(48, 37, 21));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel9.setText("Hall 1 - HU");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 130, 60));

        jLabel12.setBackground(new java.awt.Color(48, 37, 21));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel12.setText("Heaven 47 ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 60));

        jLabel13.setBackground(new java.awt.Color(48, 37, 21));
        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel13.setText("Weddings - Maadi");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 60));

        jLabel14.setBackground(new java.awt.Color(48, 37, 21));
        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel14.setText("Arena 5");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 110, 60));

        jLabel15.setBackground(new java.awt.Color(48, 37, 21));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel15.setText("Concerts - Fifth Settlement");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 220, 60));

        MakeYourBooking.setBackground(new java.awt.Color(87, 67, 41));
        MakeYourBooking.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        MakeYourBooking.setForeground(new java.awt.Color(255, 255, 255));
        MakeYourBooking.setText("Make Your Booking");
        MakeYourBooking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MakeYourBooking.setBorderPainted(false);
        MakeYourBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeYourBookingActionPerformed(evt);
            }
        });
        getContentPane().add(MakeYourBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 160, 50));

        jLabel1.setBackground(new java.awt.Color(204, 173, 140));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 562));

        SignUpNow1.setBackground(new java.awt.Color(87, 67, 41));
        SignUpNow1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        SignUpNow1.setForeground(new java.awt.Color(255, 255, 255));
        SignUpNow1.setText("Make Your Booking");
        SignUpNow1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignUpNow1.setBorderPainted(false);
        SignUpNow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpNow1ActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpNow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakeYourBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeYourBookingActionPerformed
        CustomerNewBooking myb = new CustomerNewBooking();
        myb.show();
        dispose();
    }//GEN-LAST:event_MakeYourBookingActionPerformed

    private void SignUpNow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpNow1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpNow1ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        Home lo = new Home();
        lo.show();
        dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void ContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsActionPerformed
        ContactUs ok = new ContactUs();
        ok.show();
        dispose();
    }//GEN-LAST:event_ContactUsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          Bookings bo = new Bookings();
          bo.show();
          dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContactUs;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton MakeYourBooking;
    private javax.swing.JButton SignUpNow1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
