/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ems;

/**
 *
 * @author user
 */
public class CustomersInfo extends javax.swing.JFrame {

    /**
     * Creates new form CustomersInfo
     */
    public CustomersInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOut = new javax.swing.JButton();
        ContactUs = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B1Type = new javax.swing.JLabel();
        B1ReadyDate1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        B1Type1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MakeYourBooking = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOut.setBackground(new java.awt.Color(207, 179, 138));
        LogOut.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        LogOut.setForeground(new java.awt.Color(84, 64, 40));
        LogOut.setText("Log Out");
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 15, 130, -1));

        ContactUs.setBackground(new java.awt.Color(207, 179, 138));
        ContactUs.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        ContactUs.setForeground(new java.awt.Color(84, 64, 40));
        ContactUs.setText("Customers");
        ContactUs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContactUs.setBorderPainted(false);
        ContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsActionPerformed(evt);
            }
        });
        getContentPane().add(ContactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 15, 130, -1));

        jButton2.setBackground(new java.awt.Color(207, 179, 138));
        jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(84, 64, 40));
        jButton2.setText("Pending Requests");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 15, 130, -1));

        jButton1.setBackground(new java.awt.Color(207, 179, 138));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(84, 64, 40));
        jButton1.setText("Recieved Requests");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, 130, -1));

        jLabel11.setFont(new java.awt.Font("Poppins SemiBold", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name Name.");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 30));

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome Back,");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\College\\Sophomore Year\\PL-2\\EMS 3\\Images\\lol.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jLabel20.setBackground(new java.awt.Color(48, 37, 21));
        jLabel20.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        jLabel20.setText("Phone Number");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 170, 40));

        jLabel2.setBackground(new java.awt.Color(48, 37, 21));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel2.setText("Customers Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 290, 60));

        B1Type.setBackground(new java.awt.Color(48, 37, 21));
        B1Type.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        B1Type.setText("Event Type");
        getContentPane().add(B1Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 40));

        B1ReadyDate1.setBackground(new java.awt.Color(48, 37, 21));
        B1ReadyDate1.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        B1ReadyDate1.setText("Event Type");
        getContentPane().add(B1ReadyDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 110, 40));

        jLabel25.setBackground(new java.awt.Color(48, 37, 21));
        jLabel25.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        jLabel25.setText("Last Name");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, 40));

        jLabel18.setBackground(new java.awt.Color(204, 173, 140));
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 10, 100));

        jLabel16.setBackground(new java.awt.Color(48, 37, 21));
        jLabel16.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        jLabel16.setText("First Name");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 40));

        jLabel19.setBackground(new java.awt.Color(48, 37, 21));
        jLabel19.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        jLabel19.setText("Email Address");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, 40));

        jLabel7.setBackground(new java.awt.Color(204, 173, 140));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 10, 100));

        jLabel22.setBackground(new java.awt.Color(204, 173, 140));
        jLabel22.setOpaque(true);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 10, 100));

        B1Type1.setBackground(new java.awt.Color(48, 37, 21));
        B1Type1.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        B1Type1.setText("Event Type");
        getContentPane().add(B1Type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 110, 40));

        jLabel4.setBackground(new java.awt.Color(233, 213, 192));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 950, 56));

        jLabel17.setBackground(new java.awt.Color(48, 37, 21));
        jLabel17.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        jLabel17.setText("Venue");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 80, 40));

        jLabel9.setBackground(new java.awt.Color(204, 173, 140));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 10, 100));

        MakeYourBooking.setBackground(new java.awt.Color(87, 67, 41));
        MakeYourBooking.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        MakeYourBooking.setForeground(new java.awt.Color(255, 255, 255));
        MakeYourBooking.setText("Send");
        MakeYourBooking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MakeYourBooking.setBorderPainted(false);
        MakeYourBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeYourBookingActionPerformed(evt);
            }
        });
        getContentPane().add(MakeYourBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 260, -1));

        jLabel29.setBackground(new java.awt.Color(48, 37, 21));
        jLabel29.setFont(new java.awt.Font("Poppins Medium", 2, 18)); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 40));

        jLabel1.setBackground(new java.awt.Color(204, 173, 140));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        Home lo = new Home();
        lo.show();
        dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void ContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsActionPerformed
        CustomersInfo ok = new CustomersInfo();
        ok.show();
        dispose();
    }//GEN-LAST:event_ContactUsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PendingRequests bo = new PendingRequests();
        bo.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProjectManagerRecieved s = new ProjectManagerRecieved();
        s.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MakeYourBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeYourBookingActionPerformed
        CustomerNewBooking myb = new CustomerNewBooking();
        myb.show();
        dispose();
    }//GEN-LAST:event_MakeYourBookingActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CustomersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CustomersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CustomersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CustomersInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CustomersInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel B1ReadyDate1;
    protected javax.swing.JLabel B1Type;
    protected javax.swing.JLabel B1Type1;
    private javax.swing.JButton ContactUs;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton MakeYourBooking;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
