package ems;

import java.io.IOException;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import static java.lang.constant.ConstantDescs.NULL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class CustomerNewBooking extends javax.swing.JFrame {

    /**
     * Creates new form CustomerNewBooking
     */
    public CustomerNewBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        LogOut = new javax.swing.JButton();
        ContactUs = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EventType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Venue = new javax.swing.JComboBox<>();
        Date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        SendRequest = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Duration = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        label1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        label1.setText("Your Request Has Been Sent!");

        javax.swing.GroupLayout DialogLayout = new javax.swing.GroupLayout(Dialog.getContentPane());
        Dialog.getContentPane().setLayout(DialogLayout);
        DialogLayout.setHorizontalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        DialogLayout.setVerticalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOut.setBackground(new java.awt.Color(207, 179, 138));
        LogOut.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        LogOut.setForeground(new java.awt.Color(84, 64, 40));
        LogOut.setText("Log Out");
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 15, 130, -1));

        ContactUs.setBackground(new java.awt.Color(207, 179, 138));
        ContactUs.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        ContactUs.setForeground(new java.awt.Color(84, 64, 40));
        ContactUs.setText("Contact Us");
        ContactUs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContactUs.setBorderPainted(false);
        ContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsActionPerformed(evt);
            }
        });
        getContentPane().add(ContactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 15, 130, -1));

        jButton2.setBackground(new java.awt.Color(207, 179, 138));
        jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(84, 64, 40));
        jButton2.setText("Bookings");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 15, 130, -1));

        jButton1.setBackground(new java.awt.Color(207, 179, 138));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(84, 64, 40));
        jButton1.setText("Home");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, 130, -1));

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome Back");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\College\\Sophomore Year\\PL-2\\EMS 3\\Images\\lol.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setText("Number of attendees");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        EventType.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        EventType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wedding", "Engagement", "Concert", "Conference", "Fair", "Other" }));
        EventType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventTypeActionPerformed(evt);
            }
        });
        getContentPane().add(EventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 270, 30));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setText("Duration");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setText("Venue");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel9.setText("Event Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel13.setText("Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        Venue.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        Venue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heaven_47 ", "Lamour_Hall  ", "Gardenia_Hall ", "Greek_Campus ", "Hall_1_HU ", "Arena_5" }));
        Venue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenueActionPerformed(evt);
            }
        });
        getContentPane().add(Venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 270, 30));

        Date.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        Date.setText("DD-MM-YYYY");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 270, 30));

        jLabel4.setBackground(new java.awt.Color(48, 37, 21));
        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel4.setText("Enter Your Event's Information");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 60));

        Number.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        getContentPane().add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 270, 30));

        SendRequest.setBackground(new java.awt.Color(87, 67, 41));
        SendRequest.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        SendRequest.setForeground(new java.awt.Color(255, 255, 255));
        SendRequest.setText("Send Request");
        SendRequest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SendRequest.setBorderPainted(false);
        SendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendRequestActionPerformed(evt);
            }
        });
        getContentPane().add(SendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 240, 30));

        jButton11.setBackground(new java.awt.Color(87, 67, 41));
        jButton11.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Browse");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 285, 90, 10));

        Duration.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        Duration.setText("Hours.Minutes");
        Duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurationActionPerformed(evt);
            }
        });
        getContentPane().add(Duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 270, 30));

        jLabel1.setBackground(new java.awt.Color(204, 173, 140));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventTypeActionPerformed

    private void SendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendRequestActionPerformed
        PMContact myb = new PMContact();
        myb.show();
        Booking b = new Booking();
        try {
            b.NewBooking(EventType.getSelectedItem().toString(), parseInt(Number.getText()), Venue.getSelectedItem().toString(), Date.getText(), parseDouble(Duration.getText()));
        } catch (IOException ex) {
            Logger.getLogger(CustomerNewBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_SendRequestActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Venues browse = new Venues();
        browse.show();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        Home lo = new Home();
        lo.show();
        dispose();
        
    }//GEN-LAST:event_LogOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CustomerHome ho = new CustomerHome();
        ho.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsActionPerformed
        ContactUs ok = new ContactUs();
        ok.show();
        dispose();
    }//GEN-LAST:event_ContactUsActionPerformed

    private void VenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenueActionPerformed

    private void DurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          Bookings bo = new Bookings();
          bo.show();
          dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContactUs;
    private javax.swing.JTextField Date;
    private javax.swing.JDialog Dialog;
    private javax.swing.JTextField Duration;
    private javax.swing.JComboBox<String> EventType;
    private javax.swing.JButton LogOut;
    private javax.swing.JTextField Number;
    private javax.swing.JButton SendRequest;
    private javax.swing.JComboBox<String> Venue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
